from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.31.1")


##### load rules #####
include: "rules/common.smk"
include: "rules/sv_merge.smk"
include: "rules/genotype.smk"
include: "rules/annotate_sv.smk"
include: "rules/visualize.smk"

### target_rules ####
rule all:
    input:
        get_output()