from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("7.31.1")


##### load rules #####

include: "rules/sv_merge.smk"

### target_rules ####
rule all:
    input:
        os.path.join(out_dir, "minda", config["sample_name"]+"_minda_ensemble.vcf"),