## example boiler plate config; will update as pipeline progresses
## will add later ....
samples: config/OV-004_samples.tsv
out_dir: /data1/shahs3/users/preskaa/APS017.1_Archive/ONT_SVChordinator_hg37_fix
sample_name: OV-004
reference: "hg19" # reference; valid options are hg19 or hg38
# filter for minda to look at SVs in regions of interest
filter_bed: /data1/shahs3/reference/GRCh37/hg19.chroms.bed
# specify if sequencing was done with ONT, if not assumed to be Illumina
ONT: True
## perform genotyping with sniffles2 to extract read support from normal
# note: genotyping step will not work with illumina samples
genotype:
  activate: True
  tumor_bam: /data1/shahs3/isabl_data_lake/analyses/73/04/27304/results/minimap2/SHAH_H000222_T01_07_WG02_R1.sorted.bam
  normal_bam: /data1/shahs3/isabl_data_lake/analyses/70/03/27003/results/minimap2/SHAH_H000029_N04_01_WG01_R1.sorted.bam
# annotate genes
annotate:
  activate: True
  oncokb: /data1/shahs3/reference/ref-sarcoma/241115_oncokb_cancerGeneList.tsv
  gene_annotation: /data1/shahs3/reference/GRCh37/Homo_sapiens.GRCh37.75.annotations-genes.txt
# make circos plot
visualize:
  activate: True


