## example boiler plate config; will update as pipeline progresses
## will add later ....
samples: config/AK-RT-003_samples.tsv
out_dir: /data1/shahs3/users/preskaa/ThreeByThreeSarcoma/data/APS030_3x3_fusions/germline_sv/AK-RT-003_SVChordinator
sample_name: AK-RT-003
reference: "hg38" # reference; valid options are hg19 or hg38
# filter for minda to look at SVs in regions of interest
filter_bed: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/hg38.p14.chroms.bed
## perform genotyping with sniffles2 to extract read support from normal
# note: genotyping step will not work with illumina samples
genotype:
  activate: False
  tumor_bam: /path/to/tumor_bam
  normal_bam: /path/to/normal_bam
# annotate genes
annotate:
  activate: True
  oncokb: /data1/shahs3/reference/ref-sarcoma/241115_oncokb_cancerGeneList.tsv
  gene_annotation: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/Homo_sapiens.GRCh38.111.annotations-genes.txt
# make circos plot
visualize:
  activate: True


