## example boiler plate config; will update as pipeline progresses
samples: config/samples.tsv
out_dir: /data1/shahs3/users/preskaa/ThreeByThreeSarcoma/data/APS030_3x3_fusions/somatic_sv
sample_name: sample
reference: "hg38" # reference; valid options are hg19 or hg38
# filter for minda to look at SVs in regions of interest
filter_bed: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/hg38.p14.chroms.bed
# type of SV calls; valid options are 'germline' or 'somatic'
sv_type: "somatic"
# minimum number of callers for consensus SV calls; future versions will allow for specifying technology types
min_callers: 2
## perform genotyping for somatic ONT SVs with sniffles2 to extract read support from normal
# note: genotyping step will not work if illumina samples are included or if SV calls are germline
genotype:
  activate: False
  tumor_bam: /path/to/tumor_bam
  normal_bam: /path/to/normal_bam
# annotate genes
annotate:
  activate: True
  oncokb: /data1/shahs3/reference/ref-sarcoma/241115_oncokb_cancerGeneList.tsv
  gene_annotation: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/Homo_sapiens.GRCh38.111.annotations-genes.txt
# make circos plot
visualize:
  activate: True


