## example boiler plate config; will update as pipeline progresses
## will add later ....
samples: config/AK-RT-003_samples.tsv
out_dir: /data1/shahs3/users/preskaa/APS017.1_Archive/ONT_SVChordinator_fix
sample_name: AK-RT-003
# filter for minda to look at SVs in regions of interest
filter_bed: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/hg38.p14.chroms.bed
# specify if sequencing was done with ONT, if not assumed to be Illumina
ONT: True
## perform genotyping with sniffles2 to extract read support from normal
# note: genotyping step will not work with illumina samples
genotype:
  activate: True
  tumor_bam: /data1/shahs3/isabl_data_lake/analyses/21/78/42178/results/minimap2/SHAH_H002190_T02_01_WG01_R1.sorted.bam
  normal_bam: /data1/shahs3/isabl_data_lake/analyses/21/79/42179/results/minimap2/SHAH_H002190_N02_01_WG01_R1.sorted.bam
# annotate genes
annotate:
  activate: True
  oncokb: /data1/shahs3/reference/ref-sarcoma/241115_oncokb_cancerGeneList.tsv
  gene_annotation: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/Homo_sapiens.GRCh38.111.annotations-genes.txt
# make circos plot
visualize:
  activate: True


