executor: slurm

default-resources:
  slurm_partition: componc_cpu
  slurm-logdir: "logs/{rule}"
  mem_mb: 20000
  runtime: 180

restart-times: 1
max-jobs-per-second: 3
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 300
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True
